[project]
name = "Keldysh_diagrammatics"
version = "1.0.0"

# Optional, adding this will enable direct links from the documentation
# to your source code.
#git_repo_url = "https://github.com/MYUSERNAME/MYPROJECT/"
#git_default_branch = "main"

[paths]
compile_commands = "Keldysh_mfRG/cmake-build-debug/compile_commands.json"
